# this file can be loaded by python as a module and contains
# sample input data for the touScoreModule.


applyScore = ['TTGAAAATAAAAAAAAGACTGTTTCACATGCTTGTTAAATATACATATGAGAATTTGTAATAATA',
              'GTTATAAAAGAAAACAATCTGTTTCAGATTGTCTACTTGTACCGAAAATAGTATTTATGCTGTTA',
              'TGAAACCCGAAAAAATACTGTTTCATCTTTTTCATATCTAACCTGCCTCTTTATATTTTACAGTT',
              'GCTTATTTACAAAATTACTGTTTCAATACTGCGTCTTTCTTTGAGTACAATCCCACATTTTATTC']
            

predictTou = ['TTTACAAAATTACTGTTTCAATACTGCGTCTTTCTTTGAGTACAATCCCACATTTTATTCTTTCC',
              'CCCGAAAAAATACTGTTTCATCTTTTTCATATCTAACCTGCCTCTTTATATTTTACAGTTCGACG',
              'AAAGAAAACAATCTGTTTCAGATTGTCTACTTGTACCGAAAATAGTATTTATGCTGTTAAACAAA',
              'ATAAAAAAAAGACTGTTTCACATGCTTGTTAAATATACATATGAGAATTTGTAATAATAGTACTT']

findTous = ['AAATAAAAAAAAGACTGTTTCACATGCTTGTTAAATATACATATGAGAATTTGTAATAATAGTACTTTGCTT',
            'TTAGTTTGAAAATAAAAAAAAGACTGTTTCACATGCTTGTTAAATATACATATGAGAATTTGTAATAATAGTACTTTGCTTTTTCATTGTATCA',
            'AGTCATGCTTATTTACAAAATTACTGTTTCAATACTGCGTCTTTCTTTGAGTACAATCCCACATTTTATTCTTTCCGTAATGATGATAACAATT']